/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as EnergiaSolarRouteImport } from './routes/energia-solar'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeystaticIndexRouteImport } from './routes/keystatic.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as KeystaticSplatRouteImport } from './routes/keystatic.$'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiKeystaticSplatRouteImport } from './routes/api.keystatic.$'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaSolarRoute = EnergiaSolarRouteImport.update({
  id: '/energia-solar',
  path: '/energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeystaticIndexRoute = KeystaticIndexRouteImport.update({
  id: '/keystatic/',
  path: '/keystatic/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeystaticSplatRoute = KeystaticSplatRouteImport.update({
  id: '/keystatic/$',
  path: '/keystatic/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeystaticSplatRoute = ApiKeystaticSplatRouteImport.update({
  id: '/api/keystatic/$',
  path: '/api/keystatic/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/keystatic/': typeof KeystaticIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/blog': typeof BlogIndexRoute
  '/keystatic': typeof KeystaticIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/keystatic/': typeof KeystaticIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/energia-solar'
    | '/nosotros'
    | '/productos'
    | '/blog/$slug'
    | '/keystatic/$'
    | '/blog/'
    | '/keystatic/'
    | '/api/keystatic/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/energia-solar'
    | '/nosotros'
    | '/productos'
    | '/blog/$slug'
    | '/keystatic/$'
    | '/blog'
    | '/keystatic'
    | '/api/keystatic/$'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/energia-solar'
    | '/nosotros'
    | '/productos'
    | '/blog/$slug'
    | '/keystatic/$'
    | '/blog/'
    | '/keystatic/'
    | '/api/keystatic/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EnergiaSolarRoute: typeof EnergiaSolarRoute
  NosotrosRoute: typeof NosotrosRoute
  ProductosRoute: typeof ProductosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  KeystaticSplatRoute: typeof KeystaticSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  KeystaticIndexRoute: typeof KeystaticIndexRoute
  ApiKeystaticSplatRoute: typeof ApiKeystaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia-solar': {
      id: '/energia-solar'
      path: '/energia-solar'
      fullPath: '/energia-solar'
      preLoaderRoute: typeof EnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keystatic/': {
      id: '/keystatic/'
      path: '/keystatic'
      fullPath: '/keystatic/'
      preLoaderRoute: typeof KeystaticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keystatic/$': {
      id: '/keystatic/$'
      path: '/keystatic/$'
      fullPath: '/keystatic/$'
      preLoaderRoute: typeof KeystaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keystatic/$': {
      id: '/api/keystatic/$'
      path: '/api/keystatic/$'
      fullPath: '/api/keystatic/$'
      preLoaderRoute: typeof ApiKeystaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EnergiaSolarRoute: EnergiaSolarRoute,
  NosotrosRoute: NosotrosRoute,
  ProductosRoute: ProductosRoute,
  BlogSlugRoute: BlogSlugRoute,
  KeystaticSplatRoute: KeystaticSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  KeystaticIndexRoute: KeystaticIndexRoute,
  ApiKeystaticSplatRoute: ApiKeystaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
